sudo: required
services:
   - docker

before_install:
  - docker build -t mostafamarji/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mostafamarji/react-test npm test -- --coverage

after_success:
  - docker build -t mostafamarji/multi-client ./client
  - docker build -t mostafamarji/multi-nginx ./nginx
  - docker build -t mostafamarji/multi-server ./server
  - docker build -t mostafamarji/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push mostafamarji/multi-client
  - docker push mostafamarji/multi-nginx
  - docker push mostafamarji/multi-server
  - docker push mostafamarji/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-347496713526
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

    